# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.FileField(null=True, upload_to='profilepics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
