# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0002_auto_20180606_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
