# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
