# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0002_auto_20180608_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
